/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's
 * pipe_io_contracts, keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_SMART_INPUTS_TRIAGE = {
  "claims_desk.triage_case": {
    inputs: {
      invoice: {
        concept_ref: "claims_desk.Invoice",
        json_schema: {
          description: "The invoice attached to the claim",
          properties: {
            amount: {
              description: "The invoice amount",
              title: "Amount",
              type: "number",
            },
            invoice_number: {
              description: "The invoice number",
              title: "Invoice Number",
              type: "string",
            },
          },
          required: ["invoice_number", "amount"],
          title: "claims_desk__Invoice",
          type: "object",
        },
        optional: false,
      },
      priority: {
        concept_ref: "claims_desk.Priority",
        json_schema: {
          description: "How urgently the claim needs answering, as a score",
          properties: {
            number: {
              anyOf: [
                {
                  type: "integer",
                },
                {
                  type: "number",
                },
              ],
              description: "The number",
              title: "Number",
            },
          },
          required: ["number"],
          title: "claims_desk__Priority",
          type: "object",
        },
        optional: false,
      },
      question: {
        concept_ref: "claims_desk.Question",
        json_schema: {
          description: "A question put to the claims desk",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "claims_desk__Question",
          type: "object",
        },
        optional: false,
      },
      tags: {
        concept_ref: "claims_desk.Tag",
        json_schema: {
          items: {
            description: "A short routing label written on the claim",
            properties: {
              text: {
                description: "The text",
                title: "Text",
                type: "string",
              },
            },
            required: ["text"],
            title: "claims_desk__Tag",
            type: "object",
          },
          type: "array",
        },
        optional: false,
      },
    },
    output: {
      concept_ref: "native.Text",
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;
