/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's two
 * validate views, each keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { InputForm, PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_CONTENT_MODERATION = {
  "content_moderation.approve_content": {
    inputs: {
      decision: {
        concept_ref: "content_moderation.Decision",
        item_count: null,
        json_schema: {
          description: "Moderation decision",
          properties: {
            action: {
              description: "Action to take",
              enum: ["approve", "reject"],
              title: "Action",
              type: "string",
            },
            approved: {
              description: "Whether content is approved",
              title: "Approved",
              type: "boolean",
            },
            reason: {
              description: "Reason for decision",
              title: "Reason",
              type: "string",
            },
          },
          required: ["approved", "reason", "action"],
          title: "content_moderation.Decision",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_moderation.ModerationResult",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_moderation.check_image_safety": {
    inputs: {
      content: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_moderation.SafetyScore",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_moderation.check_text_safety": {
    inputs: {
      content: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_moderation.SafetyScore",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_moderation.make_decision": {
    inputs: {
      image_score: {
        concept_ref: "content_moderation.SafetyScore",
        item_count: null,
        json_schema: {
          description: "Content safety assessment score",
          properties: {
            flagged_categories: {
              anyOf: [
                {
                  items: {},
                  type: "array",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "Categories flagged",
              title: "Flagged Categories",
            },
            safe: {
              description: "Whether content is safe",
              title: "Safe",
              type: "boolean",
            },
            score: {
              description: "Safety score 0-1",
              title: "Score",
              type: "number",
            },
          },
          required: ["score", "safe"],
          title: "content_moderation.SafetyScore",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
      text_score: {
        concept_ref: "content_moderation.SafetyScore",
        item_count: null,
        json_schema: {
          description: "Content safety assessment score",
          properties: {
            flagged_categories: {
              anyOf: [
                {
                  items: {},
                  type: "array",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "Categories flagged",
              title: "Flagged Categories",
            },
            safe: {
              description: "Whether content is safe",
              title: "Safe",
              type: "boolean",
            },
            score: {
              description: "Safety score 0-1",
              title: "Score",
              type: "number",
            },
          },
          required: ["score", "safe"],
          title: "content_moderation.SafetyScore",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_moderation.Decision",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_moderation.moderation_pipeline": {
    inputs: {
      content: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_moderation.ModerationResult",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_moderation.parallel_checks": {
    inputs: {
      content: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Composite",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_moderation.reject_content": {
    inputs: {
      decision: {
        concept_ref: "content_moderation.Decision",
        item_count: null,
        json_schema: {
          description: "Moderation decision",
          properties: {
            action: {
              description: "Action to take",
              enum: ["approve", "reject"],
              title: "Action",
              type: "string",
            },
            approved: {
              description: "Whether content is approved",
              title: "Approved",
              type: "boolean",
            },
            reason: {
              description: "Reason for decision",
              title: "Reason",
              type: "string",
            },
          },
          required: ["approved", "reason", "action"],
          title: "content_moderation.Decision",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_moderation.ModerationResult",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_moderation.route_action": {
    inputs: {
      decision: {
        concept_ref: "content_moderation.Decision",
        item_count: null,
        json_schema: {
          description: "Moderation decision",
          properties: {
            action: {
              description: "Action to take",
              enum: ["approve", "reject"],
              title: "Action",
              type: "string",
            },
            approved: {
              description: "Whether content is approved",
              title: "Approved",
              type: "boolean",
            },
            reason: {
              description: "Reason for decision",
              title: "Reason",
              type: "string",
            },
          },
          required: ["approved", "reason", "action"],
          title: "content_moderation.Decision",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_moderation.ModerationResult",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;

export const INPUT_FORM_CONTENT_MODERATION = {
  "content_moderation.approve_content": {
    fields: [
      {
        concept_ref: "content_moderation.Decision",
        description: "Moderation decision",
        fields: [
          {
            description: "Whether content is approved",
            kind: "boolean",
            name: "approved",
            required: true,
          },
          {
            description: "Reason for decision",
            kind: "text",
            name: "reason",
            required: true,
          },
          {
            choices: ["approve", "reject"],
            description: "Action to take",
            kind: "enum",
            name: "action",
            required: true,
          },
        ],
        gating: true,
        kind: "object",
        name: "decision",
        presence: "plain",
        required: true,
      },
    ],
  },
  "content_moderation.check_image_safety": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "content",
        presence: "plain",
        required: true,
      },
    ],
  },
  "content_moderation.check_text_safety": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "content",
        presence: "plain",
        required: true,
      },
    ],
  },
  "content_moderation.make_decision": {
    fields: [
      {
        concept_ref: "content_moderation.SafetyScore",
        description: "Content safety assessment score",
        fields: [
          {
            description: "Safety score 0-1",
            integer: false,
            kind: "number",
            name: "score",
            required: true,
          },
          {
            description: "Categories flagged",
            item: {
              kind: "unknown",
              required: true,
            },
            kind: "list",
            name: "flagged_categories",
            required: false,
          },
          {
            description: "Whether content is safe",
            kind: "boolean",
            name: "safe",
            required: true,
          },
        ],
        gating: true,
        kind: "object",
        name: "text_score",
        presence: "plain",
        required: true,
      },
      {
        concept_ref: "content_moderation.SafetyScore",
        description: "Content safety assessment score",
        fields: [
          {
            description: "Safety score 0-1",
            integer: false,
            kind: "number",
            name: "score",
            required: true,
          },
          {
            description: "Categories flagged",
            item: {
              kind: "unknown",
              required: true,
            },
            kind: "list",
            name: "flagged_categories",
            required: false,
          },
          {
            description: "Whether content is safe",
            kind: "boolean",
            name: "safe",
            required: true,
          },
        ],
        gating: true,
        kind: "object",
        name: "image_score",
        presence: "plain",
        required: true,
      },
    ],
  },
  "content_moderation.moderation_pipeline": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "content",
        presence: "plain",
        required: true,
      },
    ],
  },
  "content_moderation.parallel_checks": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "content",
        presence: "plain",
        required: true,
      },
    ],
  },
  "content_moderation.reject_content": {
    fields: [
      {
        concept_ref: "content_moderation.Decision",
        description: "Moderation decision",
        fields: [
          {
            description: "Whether content is approved",
            kind: "boolean",
            name: "approved",
            required: true,
          },
          {
            description: "Reason for decision",
            kind: "text",
            name: "reason",
            required: true,
          },
          {
            choices: ["approve", "reject"],
            description: "Action to take",
            kind: "enum",
            name: "action",
            required: true,
          },
        ],
        gating: true,
        kind: "object",
        name: "decision",
        presence: "plain",
        required: true,
      },
    ],
  },
  "content_moderation.route_action": {
    fields: [
      {
        concept_ref: "content_moderation.Decision",
        description: "Moderation decision",
        fields: [
          {
            description: "Whether content is approved",
            kind: "boolean",
            name: "approved",
            required: true,
          },
          {
            description: "Reason for decision",
            kind: "text",
            name: "reason",
            required: true,
          },
          {
            choices: ["approve", "reject"],
            description: "Action to take",
            kind: "enum",
            name: "action",
            required: true,
          },
        ],
        gating: true,
        kind: "object",
        name: "decision",
        presence: "plain",
        required: true,
      },
    ],
  },
} as unknown as InputForm;
