/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's two
 * validate views, each keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { InputForm, PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_AVAILABILITY_ROUTING = {
  "availability.check_day": {
    inputs: {
      day: {
        concept_ref: "native.Date",
        item_count: null,
        json_schema: {
          description:
            "A calendar date, optionally with a time of day — as precise as its source states.",
          properties: {
            date: {
              description: "The calendar date, in ISO 8601 (e.g. 2026-07-07). Always required.",
              format: "date",
              title: "Date",
              type: "string",
            },
            time: {
              anyOf: [
                {
                  format: "time",
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description:
                "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset). Include it only when the source states a time — never invent a time. Keep the UTC offset exactly when the source states one.",
              title: "Time",
            },
          },
          required: ["date"],
          title: "native.Date",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "availability.SlotCheck",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "availability.is_urgent": {
    inputs: {
      request: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.YesNo",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "availability.read_dates": {
    inputs: {
      request: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Date",
      item_count: null,
      multiplicity: "variable",
      optional: false,
    },
  },
  "availability.reply_now": {
    inputs: {
      checks: {
        concept_ref: "availability.SlotCheck",
        item_count: null,
        json_schema: {
          items: {
            description: "Whether one proposed date has a free slot",
            properties: {
              day: {
                description: "The date that was checked, in ISO 8601",
                title: "Day",
                type: "string",
              },
              is_free: {
                description: "Whether the calendar is free that day",
                title: "Is Free",
                type: "boolean",
              },
              note: {
                description: "What else is on the calendar that day",
                title: "Note",
                type: "string",
              },
            },
            required: ["day", "is_free", "note"],
            title: "availability.SlotCheck",
            type: "object",
          },
          type: "array",
        },
        multiplicity: "variable",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "availability.Reply",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "availability.reply_with_options": {
    inputs: {
      checks: {
        concept_ref: "availability.SlotCheck",
        item_count: null,
        json_schema: {
          items: {
            description: "Whether one proposed date has a free slot",
            properties: {
              day: {
                description: "The date that was checked, in ISO 8601",
                title: "Day",
                type: "string",
              },
              is_free: {
                description: "Whether the calendar is free that day",
                title: "Is Free",
                type: "boolean",
              },
              note: {
                description: "What else is on the calendar that day",
                title: "Note",
                type: "string",
              },
            },
            required: ["day", "is_free", "note"],
            title: "availability.SlotCheck",
            type: "object",
          },
          type: "array",
        },
        multiplicity: "variable",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "availability.Reply",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "availability.route_availability": {
    inputs: {
      request: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "availability.Reply",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "availability.route_reply": {
    inputs: {
      checks: {
        concept_ref: "availability.SlotCheck",
        item_count: null,
        json_schema: {
          items: {
            description: "Whether one proposed date has a free slot",
            properties: {
              day: {
                description: "The date that was checked, in ISO 8601",
                title: "Day",
                type: "string",
              },
              is_free: {
                description: "Whether the calendar is free that day",
                title: "Is Free",
                type: "boolean",
              },
              note: {
                description: "What else is on the calendar that day",
                title: "Note",
                type: "string",
              },
            },
            required: ["day", "is_free", "note"],
            title: "availability.SlotCheck",
            type: "object",
          },
          type: "array",
        },
        multiplicity: "variable",
        presence: "plain",
      },
      urgent: {
        concept_ref: "native.YesNo",
        item_count: null,
        json_schema: {
          description: "The answer to a yes/no question",
          properties: {
            yes_no: {
              description: "Whether the answer is yes (true) or no (false).",
              title: "Yes No",
              type: "boolean",
            },
          },
          required: ["yes_no"],
          title: "native.YesNo",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "availability.Reply",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;

export const INPUT_FORM_AVAILABILITY_ROUTING = {
  "availability.check_day": {
    fields: [
      {
        concept_ref: "native.Date",
        description:
          "A calendar date, optionally with a time of day — as precise as its source states.",
        fields: [
          {
            datetime: false,
            description: "The calendar date, in ISO 8601 (e.g. 2026-07-07). Always required.",
            kind: "date",
            name: "date",
            required: true,
          },
          {
            description:
              "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset). Include it only when the source states a time — never invent a time. Keep the UTC offset exactly when the source states one.",
            format: "time",
            kind: "text",
            name: "time",
            required: false,
          },
        ],
        gating: true,
        kind: "object",
        name: "day",
        presence: "plain",
        required: true,
      },
    ],
  },
  "availability.is_urgent": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "request",
        presence: "plain",
        required: true,
      },
    ],
  },
  "availability.read_dates": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "request",
        presence: "plain",
        required: true,
      },
    ],
  },
  "availability.reply_now": {
    fields: [
      {
        concept_ref: "availability.SlotCheck",
        description: "Whether one proposed date has a free slot",
        gating: false,
        item: {
          concept_ref: "availability.SlotCheck",
          description: "Whether one proposed date has a free slot",
          fields: [
            {
              description: "The date that was checked, in ISO 8601",
              kind: "text",
              name: "day",
              required: true,
            },
            {
              description: "Whether the calendar is free that day",
              kind: "boolean",
              name: "is_free",
              required: true,
            },
            {
              description: "What else is on the calendar that day",
              kind: "text",
              name: "note",
              required: true,
            },
          ],
          kind: "object",
          required: true,
        },
        kind: "list",
        name: "checks",
        presence: "plain",
        required: true,
      },
    ],
  },
  "availability.reply_with_options": {
    fields: [
      {
        concept_ref: "availability.SlotCheck",
        description: "Whether one proposed date has a free slot",
        gating: false,
        item: {
          concept_ref: "availability.SlotCheck",
          description: "Whether one proposed date has a free slot",
          fields: [
            {
              description: "The date that was checked, in ISO 8601",
              kind: "text",
              name: "day",
              required: true,
            },
            {
              description: "Whether the calendar is free that day",
              kind: "boolean",
              name: "is_free",
              required: true,
            },
            {
              description: "What else is on the calendar that day",
              kind: "text",
              name: "note",
              required: true,
            },
          ],
          kind: "object",
          required: true,
        },
        kind: "list",
        name: "checks",
        presence: "plain",
        required: true,
      },
    ],
  },
  "availability.route_availability": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "request",
        presence: "plain",
        required: true,
      },
    ],
  },
  "availability.route_reply": {
    fields: [
      {
        concept_ref: "availability.SlotCheck",
        description: "Whether one proposed date has a free slot",
        gating: false,
        item: {
          concept_ref: "availability.SlotCheck",
          description: "Whether one proposed date has a free slot",
          fields: [
            {
              description: "The date that was checked, in ISO 8601",
              kind: "text",
              name: "day",
              required: true,
            },
            {
              description: "Whether the calendar is free that day",
              kind: "boolean",
              name: "is_free",
              required: true,
            },
            {
              description: "What else is on the calendar that day",
              kind: "text",
              name: "note",
              required: true,
            },
          ],
          kind: "object",
          required: true,
        },
        kind: "list",
        name: "checks",
        presence: "plain",
        required: true,
      },
      {
        concept_ref: "native.YesNo",
        description: "The answer to a yes/no question",
        gating: true,
        kind: "boolean",
        name: "urgent",
        presence: "plain",
        required: true,
      },
    ],
  },
} as unknown as InputForm;
