/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's
 * pipe_io_contracts, keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_MULTI_OUTPUT_FANOUT = {
  "content_distribution.deep_analyze": {
    inputs: {
      document: {
        concept_ref: "native.Document",
        item_count: null,
        json_schema: {
          description: "A document",
          properties: {
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the document",
              title: "Filename",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the document",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public HTTPS URL of the document",
              title: "Public Url",
            },
            snippet: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "A text snippet or excerpt from the document",
              title: "Snippet",
            },
            title: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The title of the document or source",
              title: "Title",
            },
            url: {
              description: "The document URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
          },
          required: ["url"],
          title: "native.Document",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_distribution.Analysis",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_distribution.distribute": {
    inputs: {
      analysis: {
        concept_ref: "content_distribution.Analysis",
        item_count: null,
        json_schema: {
          description: "Deep content analysis",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "content_distribution.Analysis",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Composite",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_distribution.fanout_pipeline": {
    inputs: {
      document: {
        concept_ref: "native.Document",
        item_count: null,
        json_schema: {
          description: "A document",
          properties: {
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the document",
              title: "Filename",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the document",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public HTTPS URL of the document",
              title: "Public Url",
            },
            snippet: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "A text snippet or excerpt from the document",
              title: "Snippet",
            },
            title: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The title of the document or source",
              title: "Title",
            },
            url: {
              description: "The document URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
          },
          required: ["url"],
          title: "native.Document",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_distribution.DistributionReport",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_distribution.index_entities": {
    inputs: {
      analysis: {
        concept_ref: "content_distribution.Analysis",
        item_count: null,
        json_schema: {
          description: "Deep content analysis",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "content_distribution.Analysis",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_distribution.IndexEntry",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_distribution.log_sentiment": {
    inputs: {
      analysis: {
        concept_ref: "content_distribution.Analysis",
        item_count: null,
        json_schema: {
          description: "Deep content analysis",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "content_distribution.Analysis",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_distribution.SentimentLog",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_distribution.report": {
    inputs: {
      index_entry: {
        concept_ref: "content_distribution.IndexEntry",
        item_count: null,
        json_schema: {
          description: "Search index entry",
          properties: {
            json_obj: {
              additionalProperties: true,
              description: "The JSON object",
              title: "Json Obj",
              type: "object",
            },
          },
          required: ["json_obj"],
          title: "content_distribution.IndexEntry",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
      sentiment_log: {
        concept_ref: "content_distribution.SentimentLog",
        item_count: null,
        json_schema: {
          description: "Sentiment tracking log",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "content_distribution.SentimentLog",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
      summary: {
        concept_ref: "content_distribution.Summary",
        item_count: null,
        json_schema: {
          description: "Executive summary",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "content_distribution.Summary",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_distribution.DistributionReport",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "content_distribution.store_summary": {
    inputs: {
      analysis: {
        concept_ref: "content_distribution.Analysis",
        item_count: null,
        json_schema: {
          description: "Deep content analysis",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "content_distribution.Analysis",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "content_distribution.Summary",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;
