/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's two
 * validate views, each keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { InputForm, PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_IMAGE_PIPELINE = {
  "image_catalog.build_catalog": {
    inputs: {
      description: {
        concept_ref: "image_catalog.Description",
        item_count: null,
        json_schema: {
          description: "Text description of an image",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "image_catalog.Description",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
      tags: {
        concept_ref: "image_catalog.TagList",
        item_count: null,
        json_schema: {
          description: "List of classification tags",
          properties: {
            json_obj: {
              additionalProperties: true,
              description: "The JSON object",
              title: "Json Obj",
              type: "object",
            },
          },
          required: ["json_obj"],
          title: "image_catalog.TagList",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "image_catalog.CatalogEntry",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "image_catalog.classify_image": {
    inputs: {
      image: {
        concept_ref: "native.Image",
        item_count: null,
        json_schema: {
          description: "An image",
          properties: {
            caption: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The caption of the image",
              title: "Caption",
            },
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the image",
              title: "Filename",
            },
            height: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The height of the image, in pixels",
              title: "Height",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the image",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public URL of the image",
              title: "Public Url",
            },
            source_negative_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source negative prompt of the image",
              title: "Source Negative Prompt",
            },
            source_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source prompt of the image",
              title: "Source Prompt",
            },
            url: {
              description: "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
            width: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The width of the image, in pixels",
              title: "Width",
            },
          },
          required: ["url"],
          title: "native.Image",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "image_catalog.TagList",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "image_catalog.describe_image": {
    inputs: {
      image: {
        concept_ref: "native.Image",
        item_count: null,
        json_schema: {
          description: "An image",
          properties: {
            caption: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The caption of the image",
              title: "Caption",
            },
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the image",
              title: "Filename",
            },
            height: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The height of the image, in pixels",
              title: "Height",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the image",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public URL of the image",
              title: "Public Url",
            },
            source_negative_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source negative prompt of the image",
              title: "Source Negative Prompt",
            },
            source_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source prompt of the image",
              title: "Source Prompt",
            },
            url: {
              description: "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
            width: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The width of the image, in pixels",
              title: "Width",
            },
          },
          required: ["url"],
          title: "native.Image",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "image_catalog.Description",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "image_catalog.generate_thumbnail": {
    inputs: {
      image: {
        concept_ref: "native.Image",
        item_count: null,
        json_schema: {
          description: "An image",
          properties: {
            caption: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The caption of the image",
              title: "Caption",
            },
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the image",
              title: "Filename",
            },
            height: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The height of the image, in pixels",
              title: "Height",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the image",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public URL of the image",
              title: "Public Url",
            },
            source_negative_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source negative prompt of the image",
              title: "Source Negative Prompt",
            },
            source_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source prompt of the image",
              title: "Source Prompt",
            },
            url: {
              description: "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
            width: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The width of the image, in pixels",
              title: "Width",
            },
          },
          required: ["url"],
          title: "native.Image",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Image",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "image_catalog.image_pipeline": {
    inputs: {
      image: {
        concept_ref: "native.Image",
        item_count: null,
        json_schema: {
          description: "An image",
          properties: {
            caption: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The caption of the image",
              title: "Caption",
            },
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the image",
              title: "Filename",
            },
            height: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The height of the image, in pixels",
              title: "Height",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the image",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public URL of the image",
              title: "Public Url",
            },
            source_negative_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source negative prompt of the image",
              title: "Source Negative Prompt",
            },
            source_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source prompt of the image",
              title: "Source Prompt",
            },
            url: {
              description: "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
            width: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The width of the image, in pixels",
              title: "Width",
            },
          },
          required: ["url"],
          title: "native.Image",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "image_catalog.CatalogEntry",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
  "image_catalog.parallel_analyze": {
    inputs: {
      image: {
        concept_ref: "native.Image",
        item_count: null,
        json_schema: {
          description: "An image",
          properties: {
            caption: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The caption of the image",
              title: "Caption",
            },
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the image",
              title: "Filename",
            },
            height: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The height of the image, in pixels",
              title: "Height",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the image",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public URL of the image",
              title: "Public Url",
            },
            source_negative_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source negative prompt of the image",
              title: "Source Negative Prompt",
            },
            source_prompt: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The source prompt of the image",
              title: "Source Prompt",
            },
            url: {
              description: "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
            width: {
              anyOf: [
                {
                  exclusiveMinimum: 0,
                  type: "integer",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The width of the image, in pixels",
              title: "Width",
            },
          },
          required: ["url"],
          title: "native.Image",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Composite",
      item_count: null,
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;

export const INPUT_FORM_IMAGE_PIPELINE = {
  "image_catalog.build_catalog": {
    fields: [
      {
        concept_ref: "image_catalog.Description",
        description: "Text description of an image",
        gating: true,
        kind: "prose",
        name: "description",
        presence: "plain",
        refines: ["native.Text"],
        required: true,
      },
      {
        concept_ref: "image_catalog.TagList",
        description: "List of classification tags",
        gating: true,
        kind: "unknown",
        name: "tags",
        presence: "plain",
        refines: ["native.JSON"],
        required: true,
      },
    ],
  },
  "image_catalog.classify_image": {
    fields: [
      {
        concept_ref: "native.Image",
        description: "An image",
        gating: true,
        kind: "image",
        name: "image",
        presence: "plain",
        required: true,
      },
    ],
  },
  "image_catalog.describe_image": {
    fields: [
      {
        concept_ref: "native.Image",
        description: "An image",
        gating: true,
        kind: "image",
        name: "image",
        presence: "plain",
        required: true,
      },
    ],
  },
  "image_catalog.generate_thumbnail": {
    fields: [
      {
        concept_ref: "native.Image",
        description: "An image",
        gating: true,
        kind: "image",
        name: "image",
        presence: "plain",
        required: true,
      },
    ],
  },
  "image_catalog.image_pipeline": {
    fields: [
      {
        concept_ref: "native.Image",
        description: "An image",
        gating: true,
        kind: "image",
        name: "image",
        presence: "plain",
        required: true,
      },
    ],
  },
  "image_catalog.parallel_analyze": {
    fields: [
      {
        concept_ref: "native.Image",
        description: "An image",
        gating: true,
        kind: "image",
        name: "image",
        presence: "plain",
        required: true,
      },
    ],
  },
} as unknown as InputForm;
