/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's three
 * validate views, each keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { InputForm, OutputForm, PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_ALL_PIPE_TYPES = {
  "pipe_showcase.all_types_chain": {
    inputs: {
      document: {
        concept_ref: "native.Document",
        item_count: null,
        json_schema: {
          description: "A document",
          properties: {
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the document",
              title: "Filename",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the document",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public HTTPS URL of the document",
              title: "Public Url",
            },
            snippet: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "A text snippet or excerpt from the document",
              title: "Snippet",
            },
            title: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The title of the document or source",
              title: "Title",
            },
            url: {
              description: "The document URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
          },
          required: ["url"],
          title: "native.Document",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "pipe_showcase.FinalOutput",
      item_count: null,
      json_schema: {
        description: "Final combined output",
        properties: {
          text: {
            description: "The text",
            title: "Text",
            type: "string",
          },
        },
        required: ["text"],
        title: "pipe_showcase.FinalOutput",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
  "pipe_showcase.step_compose": {
    inputs: {
      analysis: {
        concept_ref: "pipe_showcase.Analysis",
        item_count: null,
        json_schema: {
          description: "Analytical assessment",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "pipe_showcase.Analysis",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
      search_result: {
        concept_ref: "native.SearchResult",
        item_count: null,
        json_schema: {
          $defs: {
            DocumentContent: {
              description: "A document",
              properties: {
                filename: {
                  anyOf: [
                    {
                      type: "string",
                    },
                    {
                      type: "null",
                    },
                  ],
                  default: null,
                  description: "The original filename of the document",
                  title: "Filename",
                },
                mime_type: {
                  anyOf: [
                    {
                      type: "string",
                    },
                    {
                      type: "null",
                    },
                  ],
                  default: null,
                  description: "The MIME type of the document",
                  title: "Mime Type",
                },
                public_url: {
                  anyOf: [
                    {
                      type: "string",
                    },
                    {
                      type: "null",
                    },
                  ],
                  default: null,
                  description: "The public HTTPS URL of the document",
                  title: "Public Url",
                },
                snippet: {
                  anyOf: [
                    {
                      type: "string",
                    },
                    {
                      type: "null",
                    },
                  ],
                  default: null,
                  description: "A text snippet or excerpt from the document",
                  title: "Snippet",
                },
                title: {
                  anyOf: [
                    {
                      type: "string",
                    },
                    {
                      type: "null",
                    },
                  ],
                  default: null,
                  description: "The title of the document or source",
                  title: "Title",
                },
                url: {
                  description:
                    "The document URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
                  title: "Url",
                  type: "string",
                },
              },
              required: ["url"],
              title: "DocumentContent",
              type: "object",
            },
          },
          description: "A search result with answer and sources",
          properties: {
            answer: {
              description: "The answer to the search query",
              title: "Answer",
              type: "string",
            },
            sources: {
              description: "The source documents supporting the answer",
              items: {
                $ref: "#/$defs/DocumentContent",
              },
              title: "Sources",
              type: "array",
            },
          },
          required: ["answer"],
          title: "native.SearchResult",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "pipe_showcase.FinalOutput",
      item_count: null,
      json_schema: {
        description: "Final combined output",
        properties: {
          text: {
            description: "The text",
            title: "Text",
            type: "string",
          },
        },
        required: ["text"],
        title: "pipe_showcase.FinalOutput",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
  "pipe_showcase.step_extract": {
    inputs: {
      document: {
        concept_ref: "native.Document",
        item_count: null,
        json_schema: {
          description: "A document",
          properties: {
            filename: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The original filename of the document",
              title: "Filename",
            },
            mime_type: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The MIME type of the document",
              title: "Mime Type",
            },
            public_url: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The public HTTPS URL of the document",
              title: "Public Url",
            },
            snippet: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "A text snippet or excerpt from the document",
              title: "Snippet",
            },
            title: {
              anyOf: [
                {
                  type: "string",
                },
                {
                  type: "null",
                },
              ],
              default: null,
              description: "The title of the document or source",
              title: "Title",
            },
            url: {
              description: "The document URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
              title: "Url",
              type: "string",
            },
          },
          required: ["url"],
          title: "native.Document",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Page",
      item_count: null,
      json_schema: {
        $defs: {
          ImageContent: {
            description: "An image",
            properties: {
              caption: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The caption of the image",
                title: "Caption",
              },
              filename: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The original filename of the image",
                title: "Filename",
              },
              height: {
                anyOf: [
                  {
                    exclusiveMinimum: 0,
                    type: "integer",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The height of the image, in pixels",
                title: "Height",
              },
              mime_type: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The MIME type of the image",
                title: "Mime Type",
              },
              public_url: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The public URL of the image",
                title: "Public Url",
              },
              source_negative_prompt: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The source negative prompt of the image",
                title: "Source Negative Prompt",
              },
              source_prompt: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The source prompt of the image",
                title: "Source Prompt",
              },
              url: {
                description: "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
                title: "Url",
                type: "string",
              },
              width: {
                anyOf: [
                  {
                    exclusiveMinimum: 0,
                    type: "integer",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The width of the image, in pixels",
                title: "Width",
              },
            },
            required: ["url"],
            title: "ImageContent",
            type: "object",
          },
          PageContent: {
            description:
              "The content of a page of a document, comprising text and linked images and an optional page view image",
            properties: {
              page_view: {
                anyOf: [
                  {
                    $ref: "#/$defs/ImageContent",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The screenshot of the page",
              },
              text_and_images: {
                $ref: "#/$defs/TextAndImagesContent",
                description: "The text and images content extracted from the page",
              },
            },
            required: ["text_and_images"],
            title: "PageContent",
            type: "object",
          },
          TextAndImagesContent: {
            properties: {
              images: {
                anyOf: [
                  {
                    items: {
                      $ref: "#/$defs/ImageContent",
                    },
                    type: "array",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "A list of images that were extracted from the text",
                title: "Images",
              },
              raw_html: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The raw HTML of the fetched page, if requested",
                title: "Raw Html",
              },
              text: {
                anyOf: [
                  {
                    $ref: "#/$defs/TextContent",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "A text content",
              },
            },
            title: "TextAndImagesContent",
            type: "object",
          },
          TextContent: {
            description: "A text",
            properties: {
              text: {
                description: "The text",
                title: "Text",
                type: "string",
              },
            },
            required: ["text"],
            title: "TextContent",
            type: "object",
          },
        },
        properties: {
          items: {
            items: {
              $ref: "#/$defs/PageContent",
            },
            title: "Items",
            type: "array",
          },
        },
        required: ["items"],
        title: "ListContent[PageContent]",
        type: "object",
      },
      multiplicity: "variable",
      optional: false,
    },
  },
  "pipe_showcase.step_imggen": {
    inputs: {
      analysis: {
        concept_ref: "pipe_showcase.Analysis",
        item_count: null,
        json_schema: {
          description: "Analytical assessment",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "pipe_showcase.Analysis",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Image",
      item_count: null,
      json_schema: {
        description: "An image",
        properties: {
          caption: {
            anyOf: [
              {
                type: "string",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The caption of the image",
            title: "Caption",
          },
          filename: {
            anyOf: [
              {
                type: "string",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The original filename of the image",
            title: "Filename",
          },
          height: {
            anyOf: [
              {
                exclusiveMinimum: 0,
                type: "integer",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The height of the image, in pixels",
            title: "Height",
          },
          mime_type: {
            anyOf: [
              {
                type: "string",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The MIME type of the image",
            title: "Mime Type",
          },
          public_url: {
            anyOf: [
              {
                type: "string",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The public URL of the image",
            title: "Public Url",
          },
          source_negative_prompt: {
            anyOf: [
              {
                type: "string",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The source negative prompt of the image",
            title: "Source Negative Prompt",
          },
          source_prompt: {
            anyOf: [
              {
                type: "string",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The source prompt of the image",
            title: "Source Prompt",
          },
          url: {
            description: "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
            title: "Url",
            type: "string",
          },
          width: {
            anyOf: [
              {
                exclusiveMinimum: 0,
                type: "integer",
              },
              {
                type: "null",
              },
            ],
            default: null,
            description: "The width of the image, in pixels",
            title: "Width",
          },
        },
        required: ["url"],
        title: "native.Image",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
  "pipe_showcase.step_llm": {
    inputs: {
      pages: {
        concept_ref: "native.Page",
        item_count: null,
        json_schema: {
          items: {
            $defs: {
              ImageContent: {
                description: "An image",
                properties: {
                  caption: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The caption of the image",
                    title: "Caption",
                  },
                  filename: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The original filename of the image",
                    title: "Filename",
                  },
                  height: {
                    anyOf: [
                      {
                        exclusiveMinimum: 0,
                        type: "integer",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The height of the image, in pixels",
                    title: "Height",
                  },
                  mime_type: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The MIME type of the image",
                    title: "Mime Type",
                  },
                  public_url: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The public URL of the image",
                    title: "Public Url",
                  },
                  source_negative_prompt: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The source negative prompt of the image",
                    title: "Source Negative Prompt",
                  },
                  source_prompt: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The source prompt of the image",
                    title: "Source Prompt",
                  },
                  url: {
                    description:
                      "The image URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
                    title: "Url",
                    type: "string",
                  },
                  width: {
                    anyOf: [
                      {
                        exclusiveMinimum: 0,
                        type: "integer",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The width of the image, in pixels",
                    title: "Width",
                  },
                },
                required: ["url"],
                title: "ImageContent",
                type: "object",
              },
              TextAndImagesContent: {
                properties: {
                  images: {
                    anyOf: [
                      {
                        items: {
                          $ref: "#/$defs/ImageContent",
                        },
                        type: "array",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "A list of images that were extracted from the text",
                    title: "Images",
                  },
                  raw_html: {
                    anyOf: [
                      {
                        type: "string",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "The raw HTML of the fetched page, if requested",
                    title: "Raw Html",
                  },
                  text: {
                    anyOf: [
                      {
                        $ref: "#/$defs/TextContent",
                      },
                      {
                        type: "null",
                      },
                    ],
                    default: null,
                    description: "A text content",
                  },
                },
                title: "TextAndImagesContent",
                type: "object",
              },
              TextContent: {
                description: "A text",
                properties: {
                  text: {
                    description: "The text",
                    title: "Text",
                    type: "string",
                  },
                },
                required: ["text"],
                title: "TextContent",
                type: "object",
              },
            },
            description:
              "The content of a page of a document, comprising text and linked images and an optional page view image",
            properties: {
              page_view: {
                anyOf: [
                  {
                    $ref: "#/$defs/ImageContent",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The screenshot of the page",
              },
              text_and_images: {
                $ref: "#/$defs/TextAndImagesContent",
                description: "The text and images content extracted from the page",
              },
            },
            required: ["text_and_images"],
            title: "native.Page",
            type: "object",
          },
          type: "array",
        },
        multiplicity: "variable",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "pipe_showcase.Analysis",
      item_count: null,
      json_schema: {
        description: "Analytical assessment",
        properties: {
          text: {
            description: "The text",
            title: "Text",
            type: "string",
          },
        },
        required: ["text"],
        title: "pipe_showcase.Analysis",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
  "pipe_showcase.step_search": {
    inputs: {
      analysis: {
        concept_ref: "pipe_showcase.Analysis",
        item_count: null,
        json_schema: {
          description: "Analytical assessment",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "pipe_showcase.Analysis",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.SearchResult",
      item_count: null,
      json_schema: {
        $defs: {
          DocumentContent: {
            description: "A document",
            properties: {
              filename: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The original filename of the document",
                title: "Filename",
              },
              mime_type: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The MIME type of the document",
                title: "Mime Type",
              },
              public_url: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The public HTTPS URL of the document",
                title: "Public Url",
              },
              snippet: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "A text snippet or excerpt from the document",
                title: "Snippet",
              },
              title: {
                anyOf: [
                  {
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description: "The title of the document or source",
                title: "Title",
              },
              url: {
                description:
                  "The document URL: a storage URI, an HTTP(S) URL, or a base64 data URL",
                title: "Url",
                type: "string",
              },
            },
            required: ["url"],
            title: "DocumentContent",
            type: "object",
          },
        },
        description: "A search result with answer and sources",
        properties: {
          answer: {
            description: "The answer to the search query",
            title: "Answer",
            type: "string",
          },
          sources: {
            description: "The source documents supporting the answer",
            items: {
              $ref: "#/$defs/DocumentContent",
            },
            title: "Sources",
            type: "array",
          },
        },
        required: ["answer"],
        title: "native.SearchResult",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;

export const INPUT_FORM_ALL_PIPE_TYPES = {
  "pipe_showcase.all_types_chain": {
    fields: [
      {
        concept_ref: "native.Document",
        description: "A document",
        gating: true,
        kind: "document",
        name: "document",
        presence: "plain",
        required: true,
      },
    ],
  },
  "pipe_showcase.step_compose": {
    fields: [
      {
        concept_ref: "pipe_showcase.Analysis",
        description: "Analytical assessment",
        gating: true,
        kind: "prose",
        name: "analysis",
        presence: "plain",
        refines: ["native.Text"],
        required: true,
      },
      {
        concept_ref: "native.SearchResult",
        description: "A search result with answer and sources",
        fields: [
          {
            description: "The answer to the search query",
            kind: "text",
            name: "answer",
            required: true,
          },
          {
            concept_ref: "native.Document",
            description: "The source documents supporting the answer",
            item: {
              concept_ref: "native.Document",
              description: "A document",
              kind: "document",
              required: true,
            },
            kind: "list",
            name: "sources",
            required: true,
          },
        ],
        gating: true,
        kind: "object",
        name: "search_result",
        presence: "plain",
        required: true,
      },
    ],
  },
  "pipe_showcase.step_extract": {
    fields: [
      {
        concept_ref: "native.Document",
        description: "A document",
        gating: true,
        kind: "document",
        name: "document",
        presence: "plain",
        required: true,
      },
    ],
  },
  "pipe_showcase.step_imggen": {
    fields: [
      {
        concept_ref: "pipe_showcase.Analysis",
        description: "Analytical assessment",
        gating: true,
        kind: "prose",
        name: "analysis",
        presence: "plain",
        refines: ["native.Text"],
        required: true,
      },
    ],
  },
  "pipe_showcase.step_llm": {
    fields: [
      {
        concept_ref: "native.Page",
        description:
          "The content of a page of a document, comprising text and linked images and an optional page view image",
        gating: false,
        item: {
          concept_ref: "native.Page",
          description:
            "The content of a page of a document, comprising text and linked images and an optional page view image",
          fields: [
            {
              concept_ref: "native.TextAndImages",
              description: "The text and images content extracted from the page",
              fields: [
                {
                  concept_ref: "native.Text",
                  description: "A text content",
                  kind: "prose",
                  name: "text",
                  required: false,
                },
                {
                  concept_ref: "native.Image",
                  description: "A list of images that were extracted from the text",
                  item: {
                    concept_ref: "native.Image",
                    description: "An image",
                    kind: "image",
                    required: true,
                  },
                  kind: "list",
                  name: "images",
                  required: false,
                },
                {
                  description: "The raw HTML of the fetched page, if requested",
                  kind: "text",
                  name: "raw_html",
                  required: false,
                },
              ],
              kind: "object",
              name: "text_and_images",
              required: true,
            },
            {
              concept_ref: "native.Image",
              description: "The screenshot of the page",
              kind: "image",
              name: "page_view",
              required: false,
            },
          ],
          kind: "object",
          required: true,
        },
        kind: "list",
        name: "pages",
        presence: "plain",
        required: true,
      },
    ],
  },
  "pipe_showcase.step_search": {
    fields: [
      {
        concept_ref: "pipe_showcase.Analysis",
        description: "Analytical assessment",
        gating: true,
        kind: "prose",
        name: "analysis",
        presence: "plain",
        refines: ["native.Text"],
        required: true,
      },
    ],
  },
} as unknown as InputForm;

export const OUTPUT_FORM_ALL_PIPE_TYPES = {
  "pipe_showcase.all_types_chain": {
    field: {
      concept_ref: "pipe_showcase.FinalOutput",
      description: "Final combined output",
      kind: "prose",
      name: "output",
      refines: ["native.Text"],
      required: true,
    },
  },
  "pipe_showcase.step_compose": {
    field: {
      concept_ref: "pipe_showcase.FinalOutput",
      description: "Final combined output",
      kind: "prose",
      name: "output",
      refines: ["native.Text"],
      required: true,
    },
  },
  "pipe_showcase.step_extract": {
    field: {
      concept_ref: "native.Page",
      description:
        "The content of a page of a document, comprising text and linked images and an optional page view image",
      item: {
        concept_ref: "native.Page",
        description:
          "The content of a page of a document, comprising text and linked images and an optional page view image",
        fields: [
          {
            concept_ref: "native.TextAndImages",
            description: "The text and images content extracted from the page",
            fields: [
              {
                concept_ref: "native.Text",
                description: "A text content",
                kind: "prose",
                name: "text",
                required: false,
              },
              {
                concept_ref: "native.Image",
                description: "A list of images that were extracted from the text",
                item: {
                  concept_ref: "native.Image",
                  description: "An image",
                  kind: "image",
                  required: true,
                },
                kind: "list",
                name: "images",
                required: false,
              },
              {
                description: "The raw HTML of the fetched page, if requested",
                kind: "text",
                name: "raw_html",
                required: false,
              },
            ],
            kind: "object",
            name: "text_and_images",
            required: true,
          },
          {
            concept_ref: "native.Image",
            description: "The screenshot of the page",
            kind: "image",
            name: "page_view",
            required: false,
          },
        ],
        kind: "object",
        required: true,
      },
      kind: "list",
      name: "output",
      required: true,
    },
  },
  "pipe_showcase.step_imggen": {
    field: {
      concept_ref: "native.Image",
      description: "An image",
      kind: "image",
      name: "output",
      required: true,
    },
  },
  "pipe_showcase.step_llm": {
    field: {
      concept_ref: "pipe_showcase.Analysis",
      description: "Analytical assessment",
      kind: "prose",
      name: "output",
      refines: ["native.Text"],
      required: true,
    },
  },
  "pipe_showcase.step_search": {
    field: {
      concept_ref: "native.SearchResult",
      description: "A search result with answer and sources",
      fields: [
        {
          description: "The answer to the search query",
          kind: "text",
          name: "answer",
          required: true,
        },
        {
          concept_ref: "native.Document",
          description: "The source documents supporting the answer",
          item: {
            concept_ref: "native.Document",
            description: "A document",
            kind: "document",
            required: true,
          },
          kind: "list",
          name: "sources",
          required: true,
        },
      ],
      kind: "object",
      name: "output",
      required: true,
    },
  },
} as unknown as OutputForm;
