/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's
 * pipe_io_contracts, keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_SINGLE_PIPE = {
  "text_processing.summarize": {
    inputs: {
      text: {
        concept_ref: "native.Text",
        json_schema: {
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "TextContent",
          type: "object",
        },
        optional: false,
      },
    },
    output: {
      concept_ref: "text_processing.Summary",
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;
