/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's
 * pipe_io_contracts, keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_SIMPLE_PARALLEL = {
  "text_analysis.analyze_sentiment": {
    inputs: {
      text: {
        concept_ref: "native.Text",
        json_schema: {
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "TextContent",
          type: "object",
        },
        optional: false,
      },
    },
    output: {
      concept_ref: "text_analysis.Sentiment",
      multiplicity: "single",
      optional: false,
    },
  },
  "text_analysis.dual_analysis_pipeline": {
    inputs: {
      text: {
        concept_ref: "native.Text",
        json_schema: {
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "TextContent",
          type: "object",
        },
        optional: false,
      },
    },
    output: {
      concept_ref: "text_analysis.AnalysisReport",
      multiplicity: "single",
      optional: false,
    },
  },
  "text_analysis.extract_keywords": {
    inputs: {
      text: {
        concept_ref: "native.Text",
        json_schema: {
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "TextContent",
          type: "object",
        },
        optional: false,
      },
    },
    output: {
      concept_ref: "text_analysis.Keyword",
      multiplicity: "variable",
      optional: false,
    },
  },
  "text_analysis.merge_results": {
    inputs: {
      keywords: {
        concept_ref: "text_analysis.Keyword",
        json_schema: {
          items: {
            description: "An extracted keyword with relevance score",
            properties: {
              keyword: {
                description: "The keyword text",
                title: "Keyword",
                type: "string",
              },
              relevance: {
                description: "Relevance score 0-1",
                title: "Relevance",
                type: "number",
              },
            },
            required: ["keyword", "relevance"],
            title: "text_analysis__Keyword",
            type: "object",
          },
          type: "array",
        },
        optional: false,
      },
      sentiment: {
        concept_ref: "text_analysis.Sentiment",
        json_schema: {
          description: "Sentiment analysis result",
          properties: {
            confidence: {
              description: "Confidence score 0-1",
              title: "Confidence",
              type: "number",
            },
            explanation: {
              description: "Why this sentiment was detected",
              title: "Explanation",
              type: "string",
            },
            sentiment: {
              description: "The detected sentiment",
              enum: ["positive", "negative", "neutral"],
              title: "Sentiment",
              type: "string",
            },
          },
          required: ["sentiment", "confidence", "explanation"],
          title: "text_analysis__Sentiment",
          type: "object",
        },
        optional: false,
      },
    },
    output: {
      concept_ref: "text_analysis.AnalysisReport",
      multiplicity: "single",
      optional: false,
    },
  },
  "text_analysis.parallel_analyze": {
    inputs: {
      text: {
        concept_ref: "native.Text",
        json_schema: {
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "TextContent",
          type: "object",
        },
        optional: false,
      },
    },
    output: {
      concept_ref: "native.Composite",
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;
