/**
 * Auto-generated by scripts/generate-fixtures.mjs — this bundle's three
 * validate views, each keyed by namespaced pipe_ref. DO NOT EDIT.
 * Regenerate with `make fixtures-contracts`.
 */
import type { InputForm, OutputForm, PipeIOContracts } from "@pipelex/mthds-form";

export const CONTRACTS_MEETING_TRIAGE = {
  "scheduling.decide": {
    inputs: {
      dates: {
        concept_ref: "native.Date",
        item_count: null,
        json_schema: {
          items: {
            description:
              "A calendar date, optionally with a time of day — as precise as its source states.",
            properties: {
              date: {
                description: "The calendar date, in ISO 8601 (e.g. 2026-07-07). Always required.",
                format: "date",
                title: "Date",
                type: "string",
              },
              time: {
                anyOf: [
                  {
                    format: "time",
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description:
                  "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset). Include it only when the source states a time — never invent a time. Keep the UTC offset exactly when the source states one.",
                title: "Time",
              },
            },
            required: ["date"],
            title: "native.Date",
            type: "object",
          },
          type: "array",
        },
        multiplicity: "variable",
        presence: "plain",
      },
      slot: {
        concept_ref: "native.Time",
        item_count: null,
        json_schema: {
          description:
            "A time of day, optionally with a UTC offset — as precise as its source states.",
          properties: {
            time: {
              description:
                "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset).",
              format: "time",
              title: "Time",
              type: "string",
            },
          },
          required: ["time"],
          title: "native.Time",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
      urgent: {
        concept_ref: "native.YesNo",
        item_count: null,
        json_schema: {
          description: "The answer to a yes/no question",
          properties: {
            yes_no: {
              description: "Whether the answer is yes (true) or no (false).",
              title: "Yes No",
              type: "boolean",
            },
          },
          required: ["yes_no"],
          title: "native.YesNo",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "scheduling.Verdict",
      item_count: null,
      json_schema: {
        description: "Whether the meeting request is accepted",
        properties: {
          yes_no: {
            description: "Whether the answer is yes (true) or no (false).",
            title: "Yes No",
            type: "boolean",
          },
        },
        required: ["yes_no"],
        title: "scheduling.Verdict",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
  "scheduling.is_urgent": {
    inputs: {
      request: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.YesNo",
      item_count: null,
      json_schema: {
        description: "The answer to a yes/no question",
        properties: {
          yes_no: {
            description: "Whether the answer is yes (true) or no (false).",
            title: "Yes No",
            type: "boolean",
          },
        },
        required: ["yes_no"],
        title: "native.YesNo",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
  "scheduling.read_dates": {
    inputs: {
      request: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Date",
      item_count: null,
      json_schema: {
        $defs: {
          DateContent: {
            description:
              "A calendar date, optionally with a time of day — as precise as its source states.\n\nThe optional ``time`` carries the UTC offset on its ``tzinfo`` when the source states one\n(fidelity, not normalization). Invalid states are unrepresentable by construction: no time\nwithout a date, no offset without a time.",
            properties: {
              date: {
                description: "The calendar date, in ISO 8601 (e.g. 2026-07-07). Always required.",
                format: "date",
                title: "Date",
                type: "string",
              },
              time: {
                anyOf: [
                  {
                    format: "time",
                    type: "string",
                  },
                  {
                    type: "null",
                  },
                ],
                default: null,
                description:
                  "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset). Include it only when the source states a time — never invent a time. Keep the UTC offset exactly when the source states one.",
                title: "Time",
              },
            },
            required: ["date"],
            title: "DateContent",
            type: "object",
          },
        },
        properties: {
          items: {
            items: {
              $ref: "#/$defs/DateContent",
            },
            title: "Items",
            type: "array",
          },
        },
        required: ["items"],
        title: "ListContent[DateContent]",
        type: "object",
      },
      multiplicity: "variable",
      optional: false,
    },
  },
  "scheduling.read_slot": {
    inputs: {
      request: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "native.Time",
      item_count: null,
      json_schema: {
        description:
          "A time of day, optionally with a UTC offset — as precise as its source states.",
        properties: {
          time: {
            description:
              "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset).",
            format: "time",
            title: "Time",
            type: "string",
          },
        },
        required: ["time"],
        title: "native.Time",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
  "scheduling.triage_request": {
    inputs: {
      request: {
        concept_ref: "native.Text",
        item_count: null,
        json_schema: {
          description: "A text",
          properties: {
            text: {
              description: "The text",
              title: "Text",
              type: "string",
            },
          },
          required: ["text"],
          title: "native.Text",
          type: "object",
        },
        multiplicity: "single",
        presence: "plain",
      },
    },
    output: {
      concept_ref: "scheduling.Verdict",
      item_count: null,
      json_schema: {
        description: "Whether the meeting request is accepted",
        properties: {
          yes_no: {
            description: "Whether the answer is yes (true) or no (false).",
            title: "Yes No",
            type: "boolean",
          },
        },
        required: ["yes_no"],
        title: "scheduling.Verdict",
        type: "object",
      },
      multiplicity: "single",
      optional: false,
    },
  },
} as unknown as PipeIOContracts;

export const INPUT_FORM_MEETING_TRIAGE = {
  "scheduling.decide": {
    fields: [
      {
        concept_ref: "native.Date",
        description:
          "A calendar date, optionally with a time of day — as precise as its source states.",
        gating: false,
        item: {
          concept_ref: "native.Date",
          description:
            "A calendar date, optionally with a time of day — as precise as its source states.",
          fields: [
            {
              datetime: false,
              description: "The calendar date, in ISO 8601 (e.g. 2026-07-07). Always required.",
              kind: "date",
              name: "date",
              required: true,
            },
            {
              description:
                "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset). Include it only when the source states a time — never invent a time. Keep the UTC offset exactly when the source states one.",
              format: "time",
              kind: "text",
              name: "time",
              required: false,
            },
          ],
          kind: "object",
          required: true,
        },
        kind: "list",
        name: "dates",
        presence: "plain",
        required: true,
      },
      {
        concept_ref: "native.Time",
        description:
          "A time of day, optionally with a UTC offset — as precise as its source states.",
        format: "time",
        gating: true,
        kind: "text",
        name: "slot",
        presence: "plain",
        required: true,
      },
      {
        concept_ref: "native.YesNo",
        description: "The answer to a yes/no question",
        gating: true,
        kind: "boolean",
        name: "urgent",
        presence: "plain",
        required: true,
      },
    ],
  },
  "scheduling.is_urgent": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "request",
        presence: "plain",
        required: true,
      },
    ],
  },
  "scheduling.read_dates": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "request",
        presence: "plain",
        required: true,
      },
    ],
  },
  "scheduling.read_slot": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "request",
        presence: "plain",
        required: true,
      },
    ],
  },
  "scheduling.triage_request": {
    fields: [
      {
        concept_ref: "native.Text",
        description: "A text",
        gating: true,
        kind: "prose",
        name: "request",
        presence: "plain",
        required: true,
      },
    ],
  },
} as unknown as InputForm;

export const OUTPUT_FORM_MEETING_TRIAGE = {
  "scheduling.decide": {
    field: {
      concept_ref: "scheduling.Verdict",
      description: "Whether the meeting request is accepted",
      kind: "boolean",
      name: "output",
      refines: ["native.YesNo"],
      required: true,
    },
  },
  "scheduling.is_urgent": {
    field: {
      concept_ref: "native.YesNo",
      description: "The answer to a yes/no question",
      kind: "boolean",
      name: "output",
      required: true,
    },
  },
  "scheduling.read_dates": {
    field: {
      concept_ref: "native.Date",
      description:
        "A calendar date, optionally with a time of day — as precise as its source states.",
      item: {
        concept_ref: "native.Date",
        description:
          "A calendar date, optionally with a time of day — as precise as its source states.",
        fields: [
          {
            datetime: false,
            description: "The calendar date, in ISO 8601 (e.g. 2026-07-07). Always required.",
            kind: "date",
            name: "date",
            required: true,
          },
          {
            description:
              "The time of day, in ISO 8601 (e.g. 15:40:00, or 15:40:00+02:00 with a UTC offset). Include it only when the source states a time — never invent a time. Keep the UTC offset exactly when the source states one.",
            format: "time",
            kind: "text",
            name: "time",
            required: false,
          },
        ],
        kind: "object",
        required: true,
      },
      kind: "list",
      name: "output",
      required: true,
    },
  },
  "scheduling.read_slot": {
    field: {
      concept_ref: "native.Time",
      description: "A time of day, optionally with a UTC offset — as precise as its source states.",
      format: "time",
      kind: "text",
      name: "output",
      required: true,
    },
  },
  "scheduling.triage_request": {
    field: {
      concept_ref: "scheduling.Verdict",
      description: "Whether the meeting request is accepted",
      kind: "boolean",
      name: "output",
      refines: ["native.YesNo"],
      required: true,
    },
  },
} as unknown as OutputForm;
