/**
 * Auto-generated by scripts/generate-fixtures.mjs from pipelex DRY runs.
 * DO NOT EDIT — regenerate with `make fixtures`.
 */
import type { GraphSpec } from "@graph/types";

export const DRY_SIMPLE_SEQUENCE = {
  graph_id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c",
  created_at: "2026-05-15T12:39:04.363255Z",
  pipeline_ref: {
    domain: "document_processing",
    main_pipe: "extract_analyze_report",
    entrypoint: null,
  },
  nodes: [
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_0",
      kind: "controller",
      pipe_code: "extract_analyze_report",
      pipe_type: "PipeSequence",
      description: "Full document processing pipeline",
      domain_code: "document_processing",
      status: "succeeded",
      timing: {
        started_at: "2026-05-15T12:39:04.363255Z",
        ended_at: "2026-05-15T12:39:04.406921Z",
        duration: 0.043666,
      },
      io: {
        inputs: [
          {
            name: "document",
            concept: "Document",
            content_type: "HtbYocCsZJULfvsreEKF",
            preview: null,
            size: null,
            digest: "Nuf2W",
            data: {
              url: "oOOEfoxrKJfLqHZgwaST",
              public_url: "KOOcGRboFzsiZAUvbwLw",
              mime_type: "HtbYocCsZJULfvsreEKF",
              filename: "sJLOHkauDycabHlDamjF",
              title: "gQkPBcFYsSsubdlXktrP",
              snippet: "SXpNwcONtsygjDVAJQbB",
            },
            data_text: "gQkPBcFYsSsubdlXktrP (oOOEfoxrKJfLqHZgwaST)\n  SXpNwcONtsygjDVAJQbB\n",
            data_html:
              '<a href="KOOcGRboFzsiZAUvbwLw" class="msg-document">gQkPBcFYsSsubdlXktrP</a><br/><small>SXpNwcONtsygjDVAJQbB</small>',
            extra: {},
          },
        ],
        outputs: [
          {
            name: "report",
            concept: "Report",
            content_type: null,
            preview: null,
            size: null,
            digest: "Eb5Kh",
            data: {
              text: "# Document Analysis Report\n\nanalysis: ```\nDRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n<pages>\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    \n```",
            },
            data_text:
              "                                      Document Analysis Report                                      \n\nanalysis: ``` DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet,         \ntemperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt: user_text: Analyze the\nfollowing document content thoroughly:                                                              \n\n\n• item #1:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\nimages:                                                                                             \n\nraw_html: None                                                                                      \n\n                                          page_view: None                                           \n\n• item #2:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\ni                                                                                                   \n\n                                                                                                    \n                                                                                                    \n                                                                                                    \n",
            data_html:
              "# Document Analysis Report\n\nanalysis: ```\nDRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n&lt;pages&gt;\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    \n```",
            extra: {},
          },
        ],
      },
      error: null,
      tags: {},
      metrics: {},
      execution_data: { step_count: 3 },
    },
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_1",
      kind: "operator",
      pipe_code: "extract_pages",
      pipe_type: "PipeExtract",
      description: "Extract pages from document",
      domain_code: "document_processing",
      status: "succeeded",
      timing: {
        started_at: "2026-05-15T12:39:04.368391Z",
        ended_at: "2026-05-15T12:39:04.375374Z",
        duration: 0.006983,
      },
      io: {
        inputs: [
          {
            name: "document",
            concept: "Document",
            content_type: "HtbYocCsZJULfvsreEKF",
            preview: null,
            size: null,
            digest: "Nuf2W",
            data: {
              url: "oOOEfoxrKJfLqHZgwaST",
              public_url: "KOOcGRboFzsiZAUvbwLw",
              mime_type: "HtbYocCsZJULfvsreEKF",
              filename: "sJLOHkauDycabHlDamjF",
              title: "gQkPBcFYsSsubdlXktrP",
              snippet: "SXpNwcONtsygjDVAJQbB",
            },
            data_text: "gQkPBcFYsSsubdlXktrP (oOOEfoxrKJfLqHZgwaST)\n  SXpNwcONtsygjDVAJQbB\n",
            data_html:
              '<a href="KOOcGRboFzsiZAUvbwLw" class="msg-document">gQkPBcFYsSsubdlXktrP</a><br/><small>SXpNwcONtsygjDVAJQbB</small>',
            extra: {},
          },
        ],
        outputs: [
          {
            name: "pages",
            concept: "Page",
            content_type: null,
            preview: null,
            size: null,
            digest: "DJy5D",
            data: {
              items: [
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
              ],
            },
            data_text:
              "   1    │ DRY RUN: OCR text                                                     \n────────┼───────────────────────────────────────────────────────────────────────\n   2    │ DRY RUN: OCR text                                                     \n────────┼───────────────────────────────────────────────────────────────────────\n   3    │ DRY RUN: OCR text                                                     \n────────┼───────────────────────────────────────────────────────────────────────\n   4    │ DRY RUN: OCR text                                                     \n",
            data_html:
              "<ul><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li></ul>",
            extra: {},
          },
        ],
      },
      error: null,
      tags: {},
      metrics: {},
      execution_data: {
        resolved_model: "azure-document-intelligence",
        document_stuff_name: "document",
        should_caption_images: false,
        should_include_page_views: false,
      },
    },
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_2",
      kind: "operator",
      pipe_code: "analyze_content",
      pipe_type: "PipeLLM",
      description: "Analyze extracted content",
      domain_code: "document_processing",
      status: "succeeded",
      timing: {
        started_at: "2026-05-15T12:39:04.380340Z",
        ended_at: "2026-05-15T12:39:04.390846Z",
        duration: 0.010506,
      },
      io: {
        inputs: [
          {
            name: "pages",
            concept: "Page",
            content_type: null,
            preview: null,
            size: null,
            digest: "DJy5D",
            data: {
              items: [
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
                {
                  text_and_images: {
                    text: { text: "DRY RUN: OCR text" },
                    images: [],
                    raw_html: null,
                  },
                  page_view: null,
                },
              ],
            },
            data_text:
              "   1    │ DRY RUN: OCR text                                                     \n────────┼───────────────────────────────────────────────────────────────────────\n   2    │ DRY RUN: OCR text                                                     \n────────┼───────────────────────────────────────────────────────────────────────\n   3    │ DRY RUN: OCR text                                                     \n────────┼───────────────────────────────────────────────────────────────────────\n   4    │ DRY RUN: OCR text                                                     \n",
            data_html:
              "<ul><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li><li><table><tr><th>text_and_images</th><td>DRY RUN: OCR text</td></tr></table></li></ul>",
            extra: {},
          },
        ],
        outputs: [
          {
            name: "analysis",
            concept: "Analysis",
            content_type: null,
            preview: null,
            size: null,
            digest: "MAgZX",
            data: {
              text: "DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n<pages>\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    ",
            },
            data_text:
              "DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5,      \nmax_tokens=None, prompting_target=None) • prompt=LLM Prompt: user_text: Analyze the following       \ndocument content thoroughly:                                                                        \n\n\n• item #1:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\nimages:                                                                                             \n\nraw_html: None                                                                                      \n\n                                          page_view: None                                           \n\n• item #2:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\ni                                                                                                   \n",
            data_html:
              "DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n&lt;pages&gt;\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    ",
            extra: {},
          },
        ],
      },
      error: null,
      tags: {},
      metrics: {},
      execution_data: {
        resolved_model: "claude-4.6-sonnet",
        resolved_model_for_object: "claude-4.6-sonnet",
        is_multiple_output: false,
        rendered_system_prompt: null,
        rendered_user_prompt:
          "Analyze the following document content thoroughly:\n\n<pages>\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #3:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #4:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n</pages>",
        structuring_path: "text",
      },
    },
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_3",
      kind: "operator",
      pipe_code: "compose_report",
      pipe_type: "PipeCompose",
      description: "Format analysis into final report",
      domain_code: "document_processing",
      status: "succeeded",
      timing: {
        started_at: "2026-05-15T12:39:04.395603Z",
        ended_at: "2026-05-15T12:39:04.404009Z",
        duration: 0.008406,
      },
      io: {
        inputs: [
          {
            name: "analysis",
            concept: "Analysis",
            content_type: null,
            preview: null,
            size: null,
            digest: "MAgZX",
            data: {
              text: "DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n<pages>\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    ",
            },
            data_text:
              "DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5,      \nmax_tokens=None, prompting_target=None) • prompt=LLM Prompt: user_text: Analyze the following       \ndocument content thoroughly:                                                                        \n\n\n• item #1:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\nimages:                                                                                             \n\nraw_html: None                                                                                      \n\n                                          page_view: None                                           \n\n• item #2:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\ni                                                                                                   \n",
            data_html:
              "DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n&lt;pages&gt;\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    ",
            extra: {},
          },
        ],
        outputs: [
          {
            name: "report",
            concept: "Report",
            content_type: null,
            preview: null,
            size: null,
            digest: "Eb5Kh",
            data: {
              text: "# Document Analysis Report\n\nanalysis: ```\nDRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n<pages>\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    \n```",
            },
            data_text:
              "                                      Document Analysis Report                                      \n\nanalysis: ``` DRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet,         \ntemperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt: user_text: Analyze the\nfollowing document content thoroughly:                                                              \n\n\n• item #1:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\nimages:                                                                                             \n\nraw_html: None                                                                                      \n\n                                          page_view: None                                           \n\n• item #2:                                                                                          \n\n                                          text_and_images                                           \n\ntext: ### text: DRY RUN: OCR text                                                                   \n\ni                                                                                                   \n\n                                                                                                    \n                                                                                                    \n                                                                                                    \n",
            data_html:
              "# Document Analysis Report\n\nanalysis: ```\nDRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n&lt;pages&gt;\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    \n```",
            extra: {},
          },
        ],
      },
      error: null,
      tags: {},
      metrics: {},
      execution_data: {
        compose_mode: "template",
        rendered_text:
          "# Document Analysis Report\n\nanalysis: ```\nDRY RUN: make_llm_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Analyze the following document content thoroughly:\n\n<pages>\n\n • item #1:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## images: \n\n## raw_html: None\n\n# page_view: None\n\n • item #2:\n\n# text_and_images\n\n## text: ### text: DRY RUN: OCR text\n\n## i\n    \n```",
      },
    },
  ],
  edges: [
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:edge_0",
      source: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_0",
      target: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_1",
      kind: "contains",
      label: null,
      source_stuff_digest: null,
      target_stuff_digest: null,
      meta: {},
    },
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:edge_1",
      source: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_0",
      target: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_2",
      kind: "contains",
      label: null,
      source_stuff_digest: null,
      target_stuff_digest: null,
      meta: {},
    },
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:edge_2",
      source: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_0",
      target: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_3",
      kind: "contains",
      label: null,
      source_stuff_digest: null,
      target_stuff_digest: null,
      meta: {},
    },
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:asm_edge_0",
      source: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_1",
      target: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_2",
      kind: "data",
      label: "pages",
      source_stuff_digest: null,
      target_stuff_digest: null,
      meta: {},
    },
    {
      id: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:asm_edge_1",
      source: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_2",
      target: "c7f4f16d-73b9-4c32-bfc6-69868d11834c:node_3",
      kind: "data",
      label: "analysis",
      source_stuff_digest: null,
      target_stuff_digest: null,
      meta: {},
    },
  ],
  meta: { format: "mthds", mode: "dry" },
  pipe_registry: {
    "document_processing.extract_analyze_report": {
      pipe_category: "PipeController",
      type: "PipeSequence",
      code: "extract_analyze_report",
      domain_code: "document_processing",
      description: "Full document processing pipeline",
      inputs: {
        document: {
          concept: {
            code: "Document",
            domain_code: "native",
            description: "A document",
            structure_class_name: "DocumentContent",
            refines: null,
          },
          multiplicity: null,
        },
      },
      output: {
        concept: {
          code: "Report",
          domain_code: "document_processing",
          description: "A formatted report document",
          structure_class_name: "document_processing__Report",
          refines: "native.Text",
        },
        multiplicity: null,
      },
      sequential_sub_pipes: [
        {
          pipe_code: "extract_pages",
          output_name: "pages",
          output_multiplicity: null,
          batch_params: null,
        },
        {
          pipe_code: "analyze_content",
          output_name: "analysis",
          output_multiplicity: null,
          batch_params: null,
        },
        {
          pipe_code: "compose_report",
          output_name: "report",
          output_multiplicity: null,
          batch_params: null,
        },
      ],
    },
    "document_processing.extract_pages": {
      pipe_category: "PipeOperator",
      type: "PipeExtract",
      code: "extract_pages",
      domain_code: "document_processing",
      description: "Extract pages from document",
      inputs: {
        document: {
          concept: {
            code: "Document",
            domain_code: "native",
            description: "A document",
            structure_class_name: "DocumentContent",
            refines: null,
          },
          multiplicity: null,
        },
      },
      output: {
        concept: {
          code: "Page",
          domain_code: "native",
          description:
            "The content of a page of a document, comprising text and linked images and an optional page view image",
          structure_class_name: "PageContent",
          refines: null,
        },
        multiplicity: true,
      },
      extract_choice: null,
      should_caption_images: false,
      max_page_images: null,
      should_include_page_views: false,
      page_views_dpi: null,
      render_js: null,
      include_raw_html: null,
      image_stuff_name: null,
      document_stuff_name: "document",
    },
    "document_processing.analyze_content": {
      pipe_category: "PipeOperator",
      type: "PipeLLM",
      code: "analyze_content",
      domain_code: "document_processing",
      description: "Analyze extracted content",
      inputs: {
        pages: {
          concept: {
            code: "Page",
            domain_code: "native",
            description:
              "The content of a page of a document, comprising text and linked images and an optional page view image",
            structure_class_name: "PageContent",
            refines: null,
          },
          multiplicity: true,
        },
      },
      output: {
        concept: {
          code: "Analysis",
          domain_code: "document_processing",
          description: "An analytical assessment of content",
          structure_class_name: "document_processing__Analysis",
          refines: "native.Text",
        },
        multiplicity: null,
      },
      llm_prompt_spec: {
        templating_style: null,
        system_prompt_blueprint: null,
        prompt_blueprint: {
          template: "Analyze the following document content thoroughly:\n\n@pages\n",
          templating_style: null,
          category: "llm_prompt",
          extra_context: null,
        },
        user_image_references: null,
        user_document_references: null,
        system_image_references: null,
        system_document_references: null,
      },
      llm_choices: { for_text: null, for_object: null },
      structuring_method: null,
      output_multiplicity: null,
    },
    "document_processing.compose_report": {
      pipe_category: "PipeOperator",
      type: "PipeCompose",
      code: "compose_report",
      domain_code: "document_processing",
      description: "Format analysis into final report",
      inputs: {
        analysis: {
          concept: {
            code: "Analysis",
            domain_code: "document_processing",
            description: "An analytical assessment of content",
            structure_class_name: "document_processing__Analysis",
            refines: "native.Text",
          },
          multiplicity: null,
        },
      },
      output: {
        concept: {
          code: "Report",
          domain_code: "document_processing",
          description: "A formatted report document",
          structure_class_name: "document_processing__Report",
          refines: "native.Text",
        },
        multiplicity: null,
      },
      template: '# Document Analysis Report\n\n{{ analysis|tag("analysis") }}\n',
      templating_style: null,
      category: "basic",
      extra_context: null,
      construct_blueprint: null,
    },
  },
  concept_registry: {
    "document_processing.Report": {
      code: "Report",
      domain_code: "document_processing",
      description: "A formatted report document",
      structure_class_name: "document_processing__Report",
      refines: "native.Text",
      json_schema: {
        description: "A formatted report document",
        properties: { text: { title: "Text", type: "string" } },
        required: ["text"],
        title: "document_processing__Report",
        type: "object",
      },
    },
    "native.Document": {
      code: "Document",
      domain_code: "native",
      description: "A document",
      structure_class_name: "DocumentContent",
      refines: null,
      json_schema: {
        properties: {
          url: {
            description:
              "The document URL: pipelex storage URL, HTTP/HTTPS URL, or base64 data URL",
            title: "Url",
            type: "string",
          },
          public_url: {
            anyOf: [{ type: "string" }, { type: "null" }],
            default: null,
            description: "The public HTTPS URL of the document",
            title: "Public Url",
          },
          mime_type: {
            anyOf: [{ type: "string" }, { type: "null" }],
            default: null,
            description: "The MIME type of the document",
            title: "Mime Type",
          },
          filename: {
            anyOf: [{ type: "string" }, { type: "null" }],
            default: null,
            description: "The original filename of the document",
            title: "Filename",
          },
          title: {
            anyOf: [{ type: "string" }, { type: "null" }],
            default: null,
            description: "The title of the document or source",
            title: "Title",
          },
          snippet: {
            anyOf: [{ type: "string" }, { type: "null" }],
            default: null,
            description: "A text snippet or excerpt from the document",
            title: "Snippet",
          },
        },
        required: ["url"],
        title: "DocumentContent",
        type: "object",
      },
    },
    "native.Page": {
      code: "Page",
      domain_code: "native",
      description:
        "The content of a page of a document, comprising text and linked images and an optional page view image",
      structure_class_name: "PageContent",
      refines: null,
      json_schema: {
        $defs: {
          ImageContent: {
            properties: {
              url: {
                description:
                  "The image URL: pipelex storage URL, HTTP/HTTPS URL, or base64 data URL",
                title: "Url",
                type: "string",
              },
              public_url: {
                anyOf: [{ type: "string" }, { type: "null" }],
                default: null,
                description: "The public URL of the image",
                title: "Public Url",
              },
              source_prompt: {
                anyOf: [{ type: "string" }, { type: "null" }],
                default: null,
                description: "The source prompt of the image",
                title: "Source Prompt",
              },
              source_negative_prompt: {
                anyOf: [{ type: "string" }, { type: "null" }],
                default: null,
                description: "The source negative prompt of the image",
                title: "Source Negative Prompt",
              },
              caption: {
                anyOf: [{ type: "string" }, { type: "null" }],
                default: null,
                description: "The caption of the image",
                title: "Caption",
              },
              mime_type: {
                anyOf: [{ type: "string" }, { type: "null" }],
                default: null,
                description: "The MIME type of the image",
                title: "Mime Type",
              },
              size: {
                anyOf: [{ $ref: "#/$defs/ImageSize" }, { type: "null" }],
                default: null,
                description: "The size in pixels (width and height) of the image",
              },
              filename: {
                anyOf: [{ type: "string" }, { type: "null" }],
                default: null,
                description: "The original filename of the image",
                title: "Filename",
              },
            },
            required: ["url"],
            title: "ImageContent",
            type: "object",
          },
          ImageSize: {
            properties: {
              width: { title: "Width", type: "integer" },
              height: { title: "Height", type: "integer" },
            },
            required: ["width", "height"],
            title: "ImageSize",
            type: "object",
          },
          TextAndImagesContent: {
            properties: {
              text: {
                anyOf: [{ $ref: "#/$defs/TextContent" }, { type: "null" }],
                default: null,
                description: "A text content",
              },
              images: {
                anyOf: [
                  { items: { $ref: "#/$defs/ImageContent" }, type: "array" },
                  { type: "null" },
                ],
                default: null,
                description: "A list of images that were extracted from the text",
                title: "Images",
              },
              raw_html: {
                anyOf: [{ type: "string" }, { type: "null" }],
                default: null,
                description: "The raw HTML of the fetched page, if requested",
                title: "Raw Html",
              },
            },
            title: "TextAndImagesContent",
            type: "object",
          },
          TextContent: {
            properties: { text: { title: "Text", type: "string" } },
            required: ["text"],
            title: "TextContent",
            type: "object",
          },
        },
        properties: {
          text_and_images: {
            $ref: "#/$defs/TextAndImagesContent",
            description: "The text and images content extracted from the page",
          },
          page_view: {
            anyOf: [{ $ref: "#/$defs/ImageContent" }, { type: "null" }],
            default: null,
            description: "The screenshot of the page",
          },
        },
        required: ["text_and_images"],
        title: "PageContent",
        type: "object",
      },
    },
    "document_processing.Analysis": {
      code: "Analysis",
      domain_code: "document_processing",
      description: "An analytical assessment of content",
      structure_class_name: "document_processing__Analysis",
      refines: "native.Text",
      json_schema: {
        description: "An analytical assessment of content",
        properties: { text: { title: "Text", type: "string" } },
        required: ["text"],
        title: "document_processing__Analysis",
        type: "object",
      },
    },
  },
} as unknown as GraphSpec;
