/**
 * Auto-generated by scripts/generate-fixtures.mjs from pipelex DRY runs.
 * DO NOT EDIT — regenerate with `make fixtures`.
 */
import type { GraphSpec } from "@graph/types";

export const DRY_SINGLE_PIPE = {
  graph_id: "dac3605f-298c-4113-9669-25faaa3fad33",
  created_at: "2026-07-09T10:59:37.633368Z",
  pipeline_ref: { domain: "text_processing", main_pipe: "summarize", entrypoint: null },
  nodes: [
    {
      id: "dac3605f-298c-4113-9669-25faaa3fad33:node_0",
      kind: "operator",
      pipe_code: "summarize",
      pipe_type: "PipeLLM",
      description: "Summarize input text",
      domain_code: "text_processing",
      status: "succeeded",
      skip_reason: null,
      timing: {
        started_at: "2026-07-09T10:59:37.633368Z",
        ended_at: "2026-07-09T10:59:37.648764Z",
        duration: 0.015396,
      },
      io: {
        inputs: [
          {
            name: "text",
            concept: "Text",
            content_type: null,
            preview: null,
            size: null,
            digest: "a2FND",
            data: { text: "OnBMblONJuzqdBaEqAKR" },
            data_text:
              "OnBMblONJuzqdBaEqAKR                                                                                \n",
            data_html: "OnBMblONJuzqdBaEqAKR",
            extra: {},
          },
        ],
        outputs: [
          {
            name: "summary",
            concept: "Summary",
            content_type: null,
            preview: null,
            size: null,
            digest: "NipXJ",
            data: {
              text: "DRY RUN: llm_gen_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Summarize the following text concisely:\n\n<text>\nOnBMblONJuzqdBaEqAKR\n</text>\n    ",
            },
            data_text:
              "DRY RUN: llm_gen_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5,       \nmax_tokens=None, prompting_target=None) • prompt=LLM Prompt: user_text: Summarize the following text\nconcisely:                                                                                          \n\n",
            data_html:
              "DRY RUN: llm_gen_text • llm_setting=LLMSetting(llm_handle=claude-4.6-sonnet, temperature=0.5, max_tokens=None, prompting_target=None) • prompt=LLM Prompt:\n    user_text:\n    Summarize the following text concisely:\n\n&lt;text&gt;\nOnBMblONJuzqdBaEqAKR\n&lt;/text&gt;\n    ",
            extra: {},
          },
        ],
      },
      error: null,
      tags: {},
      metrics: {},
      execution_data: {
        resolved_model: "claude-4.6-sonnet",
        resolved_model_for_object: "claude-4.6-sonnet",
        is_multiple_output: false,
        rendered_system_prompt: null,
        rendered_user_prompt:
          "Summarize the following text concisely:\n\n<text>\nOnBMblONJuzqdBaEqAKR\n</text>",
        structuring_path: "text",
      },
    },
  ],
  edges: [],
  meta: { format: "mthds", mode: "dry" },
  pipe_registry: {
    "text_processing.summarize": {
      pipe_category: "PipeOperator",
      type: "PipeLLM",
      code: "summarize",
      domain_code: "text_processing",
      description: "Summarize input text",
      inputs: {
        text: {
          concept: {
            code: "Text",
            domain_code: "native",
            description: "A text",
            structure_class_name: "TextContent",
            refines: null,
          },
          multiplicity: null,
          presence: "plain",
        },
      },
      output: {
        concept: {
          code: "Summary",
          domain_code: "text_processing",
          description: "A text summary of content",
          structure_class_name: "text_processing__Summary",
          refines: "native.Text",
        },
        multiplicity: null,
        presence: "plain",
      },
      llm_prompt_spec: {
        templating_style: null,
        system_prompt_blueprint: null,
        prompt_blueprint: {
          template: "Summarize the following text concisely:\n\n@text\n",
          templating_style: null,
          category: "llm_prompt",
          extra_context: null,
        },
        user_image_references: null,
        user_document_references: null,
        system_image_references: null,
        system_document_references: null,
      },
      llm_choices: { for_text: null, for_object: null },
      output_multiplicity: null,
    },
  },
  concept_registry: {
    "text_processing.Summary": {
      code: "Summary",
      domain_code: "text_processing",
      description: "A text summary of content",
      structure_class_name: "text_processing__Summary",
      refines: "native.Text",
      json_schema: {
        description: "A text summary of content",
        properties: { text: { title: "Text", type: "string" } },
        required: ["text"],
        title: "text_processing__Summary",
        type: "object",
      },
    },
    "native.Text": {
      code: "Text",
      domain_code: "native",
      description: "A text",
      structure_class_name: "TextContent",
      refines: null,
      json_schema: {
        properties: { text: { title: "Text", type: "string" } },
        required: ["text"],
        title: "TextContent",
        type: "object",
      },
    },
  },
} as unknown as GraphSpec;
