import type { GraphSpec } from "@graph/types";

// DRY specs are generated from real pipelex output by scripts/generate-fixtures.mjs.
// Pipeline stories import their LIVE specs directly from split per-pipeline modules
// to keep Storybook's browser test transform from loading the full LIVE catalog.

import {
  DRY_SINGLE_PIPE,
  DRY_TWO_PIPE_CHAIN,
  DRY_SIMPLE_SEQUENCE,
  DRY_LONG_SEQUENCE,
  DRY_SIMPLE_PARALLEL,
  DRY_THREE_WAY_PARALLEL,
  DRY_SIMPLE_CONDITION,
  DRY_SIMPLE_BATCH,
  DRY_CV_SCREENING,
  DRY_NESTED_SEQ_PAR_SEQ,
  DRY_NESTED_SEQ_COND_SEQ,
  DRY_BATCH_WITH_INNER_SEQ,
  DRY_DIAMOND_PATTERN,
  DRY_ALL_PIPE_TYPES,
  DRY_RAG_PIPELINE,
  DRY_IMAGE_PIPELINE,
  DRY_EMAIL_TRIAGE,
  DRY_CODE_REVIEW,
  DRY_CONTENT_MODERATION,
  DRY_WIDE_PARALLEL,
  DRY_MULTI_INPUT_CONVERGE,
  DRY_MULTI_OUTPUT_FANOUT,
  DRY_SIBLING_PARALLELS,
  DRY_DEEP_NESTING,
  DRY_ALL_CONTROLLER_TYPES,
  DRY_CV_MATCHING,
  DRY_CV_BATCH_SCREENING,
  DRY_CV_ANALYZER,
  DRY_RFP_QUALIFIER,
  DRY_MEETING_TRIAGE,
  DRY_AVAILABILITY_ROUTING,
  DRY_ALL_NATIVE_CONCEPTS,
} from "./pipelines/specs/_generated.dry";

export {
  DRY_SINGLE_PIPE,
  DRY_TWO_PIPE_CHAIN,
  DRY_SIMPLE_SEQUENCE,
  DRY_LONG_SEQUENCE,
  DRY_SIMPLE_PARALLEL,
  DRY_THREE_WAY_PARALLEL,
  DRY_SIMPLE_CONDITION,
  DRY_SIMPLE_BATCH,
  DRY_CV_SCREENING,
  DRY_NESTED_SEQ_PAR_SEQ,
  DRY_NESTED_SEQ_COND_SEQ,
  DRY_BATCH_WITH_INNER_SEQ,
  DRY_DIAMOND_PATTERN,
  DRY_ALL_PIPE_TYPES,
  DRY_RAG_PIPELINE,
  DRY_IMAGE_PIPELINE,
  DRY_EMAIL_TRIAGE,
  DRY_CODE_REVIEW,
  DRY_CONTENT_MODERATION,
  DRY_WIDE_PARALLEL,
  DRY_MULTI_INPUT_CONVERGE,
  DRY_MULTI_OUTPUT_FANOUT,
  DRY_SIBLING_PARALLELS,
  DRY_DEEP_NESTING,
  DRY_ALL_CONTROLLER_TYPES,
  DRY_CV_MATCHING,
  DRY_CV_BATCH_SCREENING,
  DRY_CV_ANALYZER,
  DRY_RFP_QUALIFIER,
  DRY_MEETING_TRIAGE,
  DRY_AVAILABILITY_ROUTING,
  DRY_ALL_NATIVE_CONCEPTS,
};

export const DRY_RUN_CATALOG: Record<string, { label: string; spec: GraphSpec }> = {
  DRY_SINGLE_PIPE: { label: "01 - Single PipeLLM", spec: DRY_SINGLE_PIPE },
  DRY_TWO_PIPE_CHAIN: { label: "02 - Two-Pipe Chain", spec: DRY_TWO_PIPE_CHAIN },
  DRY_SIMPLE_SEQUENCE: { label: "03 - Simple 3-Pipe Sequence", spec: DRY_SIMPLE_SEQUENCE },
  DRY_LONG_SEQUENCE: { label: "04 - Long 6-Pipe Sequence", spec: DRY_LONG_SEQUENCE },
  DRY_SIMPLE_PARALLEL: { label: "05 - Simple Parallel (2 branches)", spec: DRY_SIMPLE_PARALLEL },
  DRY_THREE_WAY_PARALLEL: { label: "06 - Three-Way Parallel", spec: DRY_THREE_WAY_PARALLEL },
  DRY_SIMPLE_CONDITION: { label: "07 - Simple Condition", spec: DRY_SIMPLE_CONDITION },
  DRY_SIMPLE_BATCH: { label: "08 - Simple Batch", spec: DRY_SIMPLE_BATCH },
  DRY_CV_SCREENING: { label: "09 - CV Screening Pipeline", spec: DRY_CV_SCREENING },
  DRY_NESTED_SEQ_PAR_SEQ: {
    label: "10 - Nested Seq > Parallel > Seq",
    spec: DRY_NESTED_SEQ_PAR_SEQ,
  },
  DRY_NESTED_SEQ_COND_SEQ: {
    label: "11 - Nested Seq > Condition > Seq",
    spec: DRY_NESTED_SEQ_COND_SEQ,
  },
  DRY_BATCH_WITH_INNER_SEQ: {
    label: "12 - Batch with Inner Sequence",
    spec: DRY_BATCH_WITH_INNER_SEQ,
  },
  DRY_DIAMOND_PATTERN: { label: "13 - Diamond Pattern", spec: DRY_DIAMOND_PATTERN },
  DRY_ALL_PIPE_TYPES: { label: "14 - All Pipe Types", spec: DRY_ALL_PIPE_TYPES },
  DRY_RAG_PIPELINE: { label: "15 - RAG Pipeline", spec: DRY_RAG_PIPELINE },
  DRY_IMAGE_PIPELINE: { label: "16 - Image Processing", spec: DRY_IMAGE_PIPELINE },
  DRY_EMAIL_TRIAGE: { label: "17 - Email Triage", spec: DRY_EMAIL_TRIAGE },
  DRY_CODE_REVIEW: { label: "18 - Code Review", spec: DRY_CODE_REVIEW },
  DRY_CONTENT_MODERATION: { label: "19 - Content Moderation", spec: DRY_CONTENT_MODERATION },
  DRY_WIDE_PARALLEL: { label: "20 - Wide Parallel (5 branches)", spec: DRY_WIDE_PARALLEL },
  DRY_MULTI_INPUT_CONVERGE: { label: "21 - Multi-Input Converge", spec: DRY_MULTI_INPUT_CONVERGE },
  DRY_MULTI_OUTPUT_FANOUT: { label: "22 - Multi-Output Fan-out", spec: DRY_MULTI_OUTPUT_FANOUT },
  DRY_SIBLING_PARALLELS: { label: "23 - Sibling Parallels", spec: DRY_SIBLING_PARALLELS },
  DRY_DEEP_NESTING: { label: "24 - Deep Nesting", spec: DRY_DEEP_NESTING },
  DRY_ALL_CONTROLLER_TYPES: { label: "25 - All Controller Types", spec: DRY_ALL_CONTROLLER_TYPES },
  DRY_CV_MATCHING: { label: "26 - CV Matching (Condition + Compose)", spec: DRY_CV_MATCHING },
  DRY_CV_BATCH_SCREENING: { label: "28 - CV Batch Screening", spec: DRY_CV_BATCH_SCREENING },
  DRY_CV_ANALYZER: { label: "30 - CV Analyzer (Concept Refinement)", spec: DRY_CV_ANALYZER },
  DRY_RFP_QUALIFIER: { label: "31 - RFP Qualifier (Structured Concepts)", spec: DRY_RFP_QUALIFIER },
  DRY_MEETING_TRIAGE: {
    label: "32 - Meeting Triage (Date / Time / YesNo)",
    spec: DRY_MEETING_TRIAGE,
  },
  DRY_AVAILABILITY_ROUTING: {
    label: "33 - Availability Routing (natives in controllers)",
    spec: DRY_AVAILABILITY_ROUTING,
  },
  DRY_ALL_NATIVE_CONCEPTS: {
    label: "34 - All Native Concepts",
    spec: DRY_ALL_NATIVE_CONCEPTS,
  },
};
